
name: 'wage_climate_vulnerability'
version: '1.0.0'

profile: 'wage_climate'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"


models:
  wage_climate_vulnerability:
    staging:
      materialized: view
      schema: staging
      tags: ["staging"]

    dimensions:
      materialized: table
      schema: dimensions
      tags: ["dimensions"]

    facts:
      materialized: table
      schema: facts
      tags: ["facts"]

vars:
  start_year: 2000
  end_year: 2024
